# Numpy : package for multidimentional array
## vector(1d)
## Matrix(2d or 1d)
## Create an array

In [5]:
import numpy as np 
#### shift +enter

In [6]:
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [7]:
list_of_lists=[1,2,3],[4,5,6],[7,8,9]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
np.arange(7,34)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [13]:
np.arange(10,98,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90])

In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [19]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [23]:
np.random.rand(2,4)

array([[0.35268123, 0.62644224, 0.18464794, 0.95823267],
       [0.98826822, 0.48226815, 0.34173354, 0.01713498]])

In [24]:
np.random.randn(2,4)

array([[-1.18758877, -0.12470463,  1.05043531, -0.10013674],
       [-0.122972  , -1.51687759, -1.48678273, -1.25089456]])

In [25]:
np.random.randint(1,25,10)

array([20, 12,  2,  5, 15,  2,  3,  3,  9, 18])

In [28]:
np.random.randint(2,10,5)

array([3, 8, 6, 5, 9])

In [31]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [34]:
rand_array=np.random.randint(0,10,5)
rand_array

array([3, 7, 9, 9, 9])

In [35]:
sample_array.min()

2

In [36]:
sample_array.argmin()

0

In [37]:
rand_array.argmin()

0

In [38]:
rand_array.max()

9

In [39]:
rand_array.argmax()

2

In [40]:
sample_array.argmax()

17

In [41]:
sample_array.dtype

dtype('int32')

In [42]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
a=np.random.rand(2,3)
a

array([[0.34474113, 0.33991769, 0.20365447],
       [0.80296192, 0.63268842, 0.97641209]])

In [45]:
a.T

array([[0.34474113, 0.80296192],
       [0.33991769, 0.63268842],
       [0.20365447, 0.97641209]])

In [48]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [51]:
sample_array=sample_array.reshape(9,2)
sample_array

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27]])

In [52]:
sample_array=sample_array.reshape(2,3)

ValueError: cannot reshape array of size 18 into shape (2,3)

In [55]:
sample_array[3]=100
sample_array

array([[ 10,  11],
       [ 12,  13],
       [ 14,  15],
       [100, 100],
       [ 18,  19],
       [ 20,  21],
       [ 22,  23],
       [ 24,  25],
       [ 26,  27]])

In [56]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [61]:
sample_array[0:5]

array([10, 11, 12, 13, 14])

In [64]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [65]:
sample_array[1:7]=1001
sample_array

array([  10, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99])

### code to import numpy?

In [75]:
import numpy as np

### create an array of 10 zeros with integer datatype

In [76]:
array=np.zeros(10,dtype=int)
array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### create normal distribution of shape 2x 5

In [78]:
np.random.randn(2,5)

array([[ 0.41421493,  0.20771285,  1.0475322 , -0.39321257,  0.44247853],
       [-0.00702605,  0.25576182, -0.89924803, -0.95850655, -0.54136815]])

### create unit vector of float datatype with shape 3x7

In [82]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### identity matrix of 10x10

In [84]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### output = 5,10,15,20,25

In [85]:
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

# Two dimentional array

In [86]:
import numpy as np

In [88]:
sample_matrix=np.array(([24,13,2,15],[15,54,65,23],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15, 54, 65, 23],
       [56, 76, 24,  7]])

In [89]:
sample_matrix[0][2]

2

In [90]:
sample_matrix[1][3]

23

In [91]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [95]:
sample_matrix[1:2,2:4]

array([[65, 23]])

In [96]:
sample_matrix[1:,2:]

array([[65, 23],
       [24,  7]])

In [97]:
sample_matrix[2]

array([56, 76, 24,  7])

In [98]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [99]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [100]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [101]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [102]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [103]:
np.min(sample_array)

1

In [104]:
np.max(sample_array)

30

In [105]:
np.argmin(sample_array)

0

In [106]:
np.argmax(sample_array)

29

In [107]:
np.std(sample_array) ###standard deviation

8.65544144839919

In [108]:
np.var(sample_array) ###variance

74.91666666666667

In [109]:
np.mean(sample_array) ###mean

15.5

In [110]:
array=np.random.randn(3,4)
array

array([[ 0.43502219, -0.1091975 , -1.00736521,  0.19939744],
       [ 0.42599311,  0.21807036,  0.76829124, -0.98070022],
       [-0.28122688,  0.24276847, -0.00232758, -1.68450184]])

In [111]:
np.round(array,decimals=3)

array([[ 0.435, -0.109, -1.007,  0.199],
       [ 0.426,  0.218,  0.768, -0.981],
       [-0.281,  0.243, -0.002, -1.685]])

In [113]:
fruits=np.array(["apple","orange","grapes","mango"])
np.unique(fruits)

array(['apple', 'grapes', 'mango', 'orange'], dtype='<U6')

# Pandas

In [115]:
import pandas as pd
import numpy as np

In [119]:
sports=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [120]:
sports['golf']

4

In [125]:
sports2=pd.Series([5,8,9,3],index=['cricket','football','baseball','golf'])
sports2

cricket     5
football    8
baseball    9
golf        3
dtype: int64

In [126]:
sports+sports2

baseball       NaN
basketball     NaN
cricket        6.0
football      10.0
golf           7.0
dtype: float64

In [128]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.546028  0.863477  0.926412  0.550984  0.018424
B  0.023311  0.025094  0.666807  0.770848  0.762085
C  0.151850  0.562846  0.360730  0.841401  0.436997
D  0.746359  0.643501  0.956679  0.310252  0.033562
E  0.219350  0.259842  0.371740  0.292498  0.065147
F  0.341143  0.885008  0.277377  0.801674  0.188109
G  0.828357  0.961312  0.801981  0.440207  0.174314
H  0.843699  0.027912  0.331550  0.659921  0.405383

In [130]:
df1['Score2']

A    0.863477
B    0.025094
C    0.562846
D    0.643501
E    0.259842
F    0.885008
G    0.961312
H    0.027912
Name: Score2, dtype: float64

In [131]:
df1[['Score1','Score2','Score3']]

Score1    Score2    Score3
A  0.546028  0.863477  0.926412
B  0.023311  0.025094  0.666807
C  0.151850  0.562846  0.360730
D  0.746359  0.643501  0.956679
E  0.219350  0.259842  0.371740
F  0.341143  0.885008  0.277377
G  0.828357  0.961312  0.801981
H  0.843699  0.027912  0.331550

In [132]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.546028  0.863477  0.926412  0.550984  0.018424  1.409505
B  0.023311  0.025094  0.666807  0.770848  0.762085  0.048405
C  0.151850  0.562846  0.360730  0.841401  0.436997  0.714697
D  0.746359  0.643501  0.956679  0.310252  0.033562  1.389860
E  0.219350  0.259842  0.371740  0.292498  0.065147  0.479192
F  0.341143  0.885008  0.277377  0.801674  0.188109  1.226151
G  0.828357  0.961312  0.801981  0.440207  0.174314  1.789669
H  0.843699  0.027912  0.331550  0.659921  0.405383  0.871611

In [136]:
df1.drop('Score3',axis=1)

Score1    Score2    Score4    Score5    Score6
A  0.546028  0.863477  0.550984  0.018424  1.409505
B  0.023311  0.025094  0.770848  0.762085  0.048405
C  0.151850  0.562846  0.841401  0.436997  0.714697
D  0.746359  0.643501  0.310252  0.033562  1.389860
E  0.219350  0.259842  0.292498  0.065147  0.479192
F  0.341143  0.885008  0.801674  0.188109  1.226151
G  0.828357  0.961312  0.440207  0.174314  1.789669
H  0.843699  0.027912  0.659921  0.405383  0.871611

In [137]:
df1.drop('E')

Score1    Score2    Score3    Score4    Score5    Score6
A  0.546028  0.863477  0.926412  0.550984  0.018424  1.409505
B  0.023311  0.025094  0.666807  0.770848  0.762085  0.048405
C  0.151850  0.562846  0.360730  0.841401  0.436997  0.714697
D  0.746359  0.643501  0.956679  0.310252  0.033562  1.389860
F  0.341143  0.885008  0.277377  0.801674  0.188109  1.226151
G  0.828357  0.961312  0.801981  0.440207  0.174314  1.789669
H  0.843699  0.027912  0.331550  0.659921  0.405383  0.871611

In [138]:
df1.drop(["Score1","Score2"],axis=1)

Score3    Score4    Score5    Score6
A  0.926412  0.550984  0.018424  1.409505
B  0.666807  0.770848  0.762085  0.048405
C  0.360730  0.841401  0.436997  0.714697
D  0.956679  0.310252  0.033562  1.389860
E  0.371740  0.292498  0.065147  0.479192
F  0.277377  0.801674  0.188109  1.226151
G  0.801981  0.440207  0.174314  1.789669
H  0.331550  0.659921  0.405383  0.871611

In [139]:
df2={'ID':[101,102,103,107,176],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [140]:
df.drop('ID',axis=1)


Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
3  Kavin      87
4  Lally     123

In [141]:
df.drop(3)

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
4  176  Lally     123

In [142]:
df[['Name','Profit']]


Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
3  Kavin      87
4  Lally     123

In [143]:
df[['Name','ID']]


Name   ID
0   John  101
1  Mercy  102
2  Akash  103
3  Kavin  107
4  Lally  176